### PR TITLE
Add make_exhibit.py cookiecutter script

### LINKED ISSUE #32: Cookie cutter
@JessyD created https://github.com/JessyD/model-zoo-cookiecutter

Haven't had a chance to play with it yet, but don't want this to get lost in my personal notes.

### PR DESCRIPTION
**Pull request by JessyD**
Closes #32 
_____
Edit by @adelavega:

I took @JessyD's cookiecutter and added several functions (thanks @JessyD!)

The "make_exhibit.py" cookie-cutter derived script will allow users to easily create new model-zoo examples with a simple CLI command.

```
Usage: make_exhibit.py [OPTIONS]

Options:
  --exhibit-name TEXT     Name of the exhibit. This will be the name of the
                          folder that will be created under model-
                          zoo/exhibits.  [required]
  --model-json-path TEXT  Path to a BIDS Stats Model file ending in
                          _smdl.json. File will be copied into the exhibit
                          folder.          If not provided, an incomplete
                          default model will be placed in the exhibit folder
                          as a starting point.
  --dataset-url TEXT      DataLad URL of the RAW dataset to install as a
                          submodule. If not provided, no dataset will be
                          installed, and user will have to manually install it
                          later.
  --preproc-url TEXT      DataLad URL of the PREPROCESSED dataset. If None,
                          its assumed the preprocessed data is under
                          /derivatives/ in the RAW dataset.
  --scan-length INTEGER   Length of the scan in seconds. Used to create design
                          matices without downloading functional images.
  --description TEXT      Description of the BIDS Stats Model.
  --toc / --no-toc        Update the table of contents with new example?
  --help                  Show this message and exit.
```

Some notes:
 - I wrapped cookiecutter with a custom click CLI, to allow direct CLI use (rather than prompts, which I found harder to paste links and paths into)
 - While cookiecutter is nice, the hooks are quite limited in capability, so in `make_exhibit.py` I'm able to pre-process inputs that will be later injected into the templates (i.e. `.md` file). 
 - Only `exhibit-name` is required. If datasets are not provided, they are not installed (but a user will eventually need to). If a model is not provided, an incomplete model is put in place. There is also a default `.md` tempalte that is pre-populated with user-given variables and pointing to the correct `.json` model and datasets
 - Datasets are installed using datalad as a submodule
 - By default, the model-zoo `_toc.yml` is updated with the new example, but this can be switched off with the `--no-toc` flag

### CODE REVIEW

**Comment by adelavega** [comment]
I pushed some commits to reorganize a bit. Looks good, but I'd like to add the `datalad` submodule thing to this, rather than making a local symlink, as I think that makes the examples fully reproducible (remotely).

Looks good otherwise though! Can you take care of that or shall I?

**Comment by JessyD** [comment]
My knowledge about datalad is quite limited, so I think it might be faster if you do it.

**Comment by adelavega** [comment]
TODO

- [ ] Add git sub module setup
- [ ] Create skeleton BSM

**Comment by adelavega** [comment]
Jeannette: Test without optional argument -- bug without specifying all args

**Comment by adelavega** [comment]
@jmumford your issue should be fixed.

@effigies do you want to give this a review or should we call it good?

**Pull request merged**
