### PR TITLE
add models for SPM block design tutos

### PR DESCRIPTION
**Pull request by Remi-Gau**
replaces #1 

## TODO

- [ ] Make it work with fitlins

### CODE REVIEW

**Comment by shashankbansal6** [comment]
I believe we moved type into `Model`
Something like this: ` "Model": {"X": [1], "Type": "Meta"},`
Ref: https://github.com/bids-standard/model-zoo/blob/6b38841de2d21612933917a661a88b95c93b1ced/narps/model/model-narps_smdl.json#L48

**Comment by Remi-Gau** [comment]
> I believe we moved type into `Model`

Oh gosh. That JSON has like 10 lines and I managed to F it up. Thanks for catching this.

**Comment by Remi-Gau** [comment]
Currently this fails to run with fitlins:

```bash
$ bash moae_run_fitlins.sh

Captured warning (<class 'FutureWarning'>): Fetchers from the nilearn.datasets module will be updated in version 0.9 to return python strings instead of bytes and Pandas dataframes instead of Numpy arrays.
Traceback (most recent call last):
  File "/home/remi/github/BIDS-model-zoo/spm_tutorials/env/bin/fitlins", line 8, in <module>
    sys.exit(main())
  File "/home/remi/github/BIDS-model-zoo/spm_tutorials/env/lib/python3.8/site-packages/fitlins/cli/run.py", line 432, in main
    sys.exit(run_fitlins(sys.argv[1:]))
  File "/home/remi/github/BIDS-model-zoo/spm_tutorials/env/lib/python3.8/site-packages/fitlins/cli/run.py", line 385, in run_fitlins
    fitlins_wf = init_fitlins_wf(
  File "/home/remi/github/BIDS-model-zoo/spm_tutorials/env/lib/python3.8/site-packages/fitlins/workflows/base.py", line 285, in init_fitlins_wf
    select_specs = pe.Node(
  File "/home/remi/github/BIDS-model-zoo/spm_tutorials/env/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 181, in __init__
    super(Node, self).__init__(name, kwargs.get("base_dir"))
  File "/home/remi/github/BIDS-model-zoo/spm_tutorials/env/lib/python3.8/site-packages/nipype/pipeline/engine/base.py", line 37, in __init__
    self.name = name
  File "/home/remi/github/BIDS-model-zoo/spm_tutorials/env/lib/python3.8/site-packages/nipype/pipeline/engine/base.py", line 53, in name
    raise ValueError('[Workflow|Node] name "%s" is not valid.' % name)
ValueError: [Workflow|Node] name "select_run level_specs" is not valid.
```

**Comment by adelavega** [comment]
Hey, this is really nice! I like how reproducible it all is.

A more general concern I have is that I'm hoping that all model zoo examples eventually follow a similar format, so that they can eventually be displayed in a Jupyter Book or equivalent website, and run in Binder.

I'll probably hold off on merging until we have that, but this looks very compatible.

**Comment by Remi-Gau** [comment]
Well some of the stuff for fitlins are also there because I wanted to make it easier for others to run it and help me figure out what is wrong with this model and why it can't run.

**Comment by shashankbansal6** [comment]
Finally, after all of this fixes, it should run the FirstLevelModel and you will get all of the first level images but I just discovered a bug in fitlins reports where its [hard-coded](https://github.com/poldracklab/fitlins/blob/dev/fitlins/viz/reports.py#L128-L131) to expect a subject level node so it will throw the following error:
```
Traceback (most recent call last):
  File "/Users/shashankbansal/miniconda/envs/spm_tuto/bin/fitlins", line 8, in <module>
    sys.exit(main())
  File "/Users/shashankbansal/miniconda/envs/spm_tuto/lib/python3.8/site-packages/fitlins/cli/run.py", line 432, in main
    sys.exit(run_fitlins(sys.argv[1:]))
  File "/Users/shashankbansal/miniconda/envs/spm_tuto/lib/python3.8/site-packages/fitlins/cli/run.py", line 425, in run_fitlins
    report_dict = build_report_dict(deriv_dir, work_dir, graph)
  File "/Users/shashankbansal/miniconda/envs/spm_tuto/lib/python3.8/site-packages/fitlins/viz/reports.py", line 130, in build_report_dict
    {analysis_dict['entities']['subject'] for analysis_dict in report['nodes'][0]['analyses']}
  File "/Users/shashankbansal/miniconda/envs/spm_tuto/lib/python3.8/site-packages/fitlins/viz/reports.py", line 130, in <setcomp>
    {analysis_dict['entities']['subject'] for analysis_dict in report['nodes'][0]['analyses']}
KeyError: 'subject'
```
I have created a [new issue](https://github.com/poldracklab/fitlins/issues/366) in fitlins to keep track.

**Comment by adelavega** [comment]
Should we merge and later change things to a the uniform environment once that is better defined?

**Comment by Remi-Gau** [comment]
> Should we merge and later change things to a the uniform environment once that is better defined?

good with me

this may also include some change, once this is runnable with fitlins

**Pull request merged**
